// Auto-generated by generate_data.py; do not edit.
// Source: common\AtkParam_Pc.json

use serde::{Deserialize, Serialize};

use crate::records::SearchField;
use crate::traits::Searchable;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AtkParamPc {
    #[serde(rename = "ID")]
    pub id: i64,

    #[serde(rename = "Name")]
    pub name: String,

    #[serde(rename = "hit0_Radius")]
    pub hit0_radius: f64,

    #[serde(rename = "hit1_Radius")]
    pub hit1_radius: f64,

    #[serde(rename = "hit2_Radius")]
    pub hit2_radius: f64,

    #[serde(rename = "hit3_Radius")]
    pub hit3_radius: f64,

    pub knockback_dist: f64,

    pub hit_stop_time: f64,

    pub sp_effect_id0: i64,

    pub sp_effect_id1: i64,

    pub sp_effect_id2: i64,

    pub sp_effect_id3: i64,

    pub sp_effect_id4: i64,

    #[serde(rename = "hit0_DmyPoly1")]
    pub hit0_dmy_poly1: i64,

    #[serde(rename = "hit1_DmyPoly1")]
    pub hit1_dmy_poly1: i64,

    #[serde(rename = "hit2_DmyPoly1")]
    pub hit2_dmy_poly1: i64,

    #[serde(rename = "hit3_DmyPoly1")]
    pub hit3_dmy_poly1: i64,

    #[serde(rename = "hit0_DmyPoly2")]
    pub hit0_dmy_poly2: i64,

    #[serde(rename = "hit1_DmyPoly2")]
    pub hit1_dmy_poly2: i64,

    #[serde(rename = "hit2_DmyPoly2")]
    pub hit2_dmy_poly2: i64,

    #[serde(rename = "hit3_DmyPoly2")]
    pub hit3_dmy_poly2: i64,

    pub blowing_correction: i64,

    pub atk_phys_correction: i64,

    pub atk_mag_correction: i64,

    pub atk_fire_correction: i64,

    pub atk_thun_correction: i64,

    pub atk_stam_correction: i64,

    pub guard_atk_rate_correction: i64,

    pub guard_break_correction: i64,

    pub atk_throw_escape_correction: i64,

    pub sub_category1: i64,

    pub sub_category2: i64,

    pub atk_phys: i64,

    pub atk_mag: i64,

    pub atk_fire: i64,

    pub atk_thun: i64,

    pub atk_stam: i64,

    pub guard_atk_rate: i64,

    pub guard_break_rate: i64,

    pub pad6: i64,

    pub is_enable_calc_damage_for_bushes_obj: i64,

    pub atk_throw_escape: i64,

    pub atk_obj: i64,

    pub guard_stamina_cut_rate: i64,

    pub guard_rate: i64,

    pub throw_type_id: i64,

    #[serde(rename = "hit0_hitType")]
    pub hit0_hit_type: i64,

    #[serde(rename = "hit1_hitType")]
    pub hit1_hit_type: i64,

    #[serde(rename = "hit2_hitType")]
    pub hit2_hit_type: i64,

    #[serde(rename = "hit3_hitType")]
    pub hit3_hit_type: i64,

    #[serde(rename = "hti0_Priority")]
    pub hti0_priority: i64,

    #[serde(rename = "hti1_Priority")]
    pub hti1_priority: i64,

    #[serde(rename = "hti2_Priority")]
    pub hti2_priority: i64,

    #[serde(rename = "hti3_Priority")]
    pub hti3_priority: i64,

    pub dmg_level: i64,

    pub map_hit_type: i64,

    pub guard_cut_cancel_rate: i64,

    pub atk_attribute: i64,

    pub sp_attribute: i64,

    pub atk_type: i64,

    pub atk_material: i64,

    pub guard_range_type: i64,

    pub def_se_material1: i64,

    pub hit_source_type: i64,

    pub throw_flag: i64,

    pub disable_guard: i64,

    pub disable_stamina_attack: i64,

    pub disable_hit_sp_effect: i64,

    #[serde(rename = "IgnoreNotifyMissSwingForAI")]
    pub ignore_notify_miss_swing_for_ai: i64,

    pub repeat_hit_sfx: i64,

    pub is_arrow_atk: i64,

    pub is_ghost_atk: i64,

    pub is_disable_no_damage: i64,

    #[serde(rename = "atkPow_forSfx")]
    pub atk_pow_for_sfx: i64,

    #[serde(rename = "atkDir_forSfx")]
    pub atk_dir_for_sfx: i64,

    pub oppose_target: i64,

    pub friendly_target: i64,

    pub self_target: i64,

    pub is_check_door_penetration: i64,

    pub is_vs_ride_atk: i64,

    pub is_add_base_atk: i64,

    pub exclude_threat_lv_notify: i64,

    pub pad1: i64,

    pub atk_behavior_id: i64,

    #[serde(rename = "atkPow_forSe")]
    pub atk_pow_for_se: i64,

    pub atk_super_armor: f64,

    pub decal_id1: i64,

    pub decal_id2: i64,

    #[serde(rename = "AppearAiSoundId")]
    pub appear_ai_sound_id: i64,

    #[serde(rename = "HitAiSoundId")]
    pub hit_ai_sound_id: i64,

    #[serde(rename = "HitRumbleId")]
    pub hit_rumble_id: i64,

    #[serde(rename = "HitRumbleIdByNormal")]
    pub hit_rumble_id_by_normal: i64,

    #[serde(rename = "HitRumbleIdByMiddle")]
    pub hit_rumble_id_by_middle: i64,

    #[serde(rename = "HitRumbleIdByRoot")]
    pub hit_rumble_id_by_root: i64,

    pub trace_sfx_id0: i64,

    pub trace_dmy_id_head0: i64,

    pub trace_dmy_id_tail0: i64,

    pub trace_sfx_id1: i64,

    pub trace_dmy_id_head1: i64,

    pub trace_dmy_id_tail1: i64,

    pub trace_sfx_id2: i64,

    pub trace_dmy_id_head2: i64,

    pub trace_dmy_id_tail2: i64,

    pub trace_sfx_id3: i64,

    pub trace_dmy_id_head3: i64,

    pub trace_dmy_id_tail3: i64,

    pub trace_sfx_id4: i64,

    pub trace_dmy_id_head4: i64,

    pub trace_dmy_id_tail4: i64,

    pub trace_sfx_id5: i64,

    pub trace_dmy_id_head5: i64,

    pub trace_dmy_id_tail5: i64,

    pub trace_sfx_id6: i64,

    pub trace_dmy_id_head6: i64,

    pub trace_dmy_id_tail6: i64,

    pub trace_sfx_id7: i64,

    pub trace_dmy_id_head7: i64,

    pub trace_dmy_id_tail7: i64,

    #[serde(rename = "hit4_Radius")]
    pub hit4_radius: f64,

    #[serde(rename = "hit5_Radius")]
    pub hit5_radius: f64,

    #[serde(rename = "hit6_Radius")]
    pub hit6_radius: i64,

    #[serde(rename = "hit7_Radius")]
    pub hit7_radius: i64,

    #[serde(rename = "hit8_Radius")]
    pub hit8_radius: i64,

    #[serde(rename = "hit9_Radius")]
    pub hit9_radius: i64,

    #[serde(rename = "hit10_Radius")]
    pub hit10_radius: i64,

    #[serde(rename = "hit11_Radius")]
    pub hit11_radius: i64,

    #[serde(rename = "hit12_Radius")]
    pub hit12_radius: i64,

    #[serde(rename = "hit13_Radius")]
    pub hit13_radius: i64,

    #[serde(rename = "hit14_Radius")]
    pub hit14_radius: i64,

    #[serde(rename = "hit15_Radius")]
    pub hit15_radius: i64,

    #[serde(rename = "hit4_DmyPoly1")]
    pub hit4_dmy_poly1: i64,

    #[serde(rename = "hit5_DmyPoly1")]
    pub hit5_dmy_poly1: i64,

    #[serde(rename = "hit6_DmyPoly1")]
    pub hit6_dmy_poly1: i64,

    #[serde(rename = "hit7_DmyPoly1")]
    pub hit7_dmy_poly1: i64,

    #[serde(rename = "hit8_DmyPoly1")]
    pub hit8_dmy_poly1: i64,

    #[serde(rename = "hit9_DmyPoly1")]
    pub hit9_dmy_poly1: i64,

    #[serde(rename = "hit10_DmyPoly1")]
    pub hit10_dmy_poly1: i64,

    #[serde(rename = "hit11_DmyPoly1")]
    pub hit11_dmy_poly1: i64,

    #[serde(rename = "hit12_DmyPoly1")]
    pub hit12_dmy_poly1: i64,

    #[serde(rename = "hit13_DmyPoly1")]
    pub hit13_dmy_poly1: i64,

    #[serde(rename = "hit14_DmyPoly1")]
    pub hit14_dmy_poly1: i64,

    #[serde(rename = "hit15_DmyPoly1")]
    pub hit15_dmy_poly1: i64,

    #[serde(rename = "hit4_DmyPoly2")]
    pub hit4_dmy_poly2: i64,

    #[serde(rename = "hit5_DmyPoly2")]
    pub hit5_dmy_poly2: i64,

    #[serde(rename = "hit6_DmyPoly2")]
    pub hit6_dmy_poly2: i64,

    #[serde(rename = "hit7_DmyPoly2")]
    pub hit7_dmy_poly2: i64,

    #[serde(rename = "hit8_DmyPoly2")]
    pub hit8_dmy_poly2: i64,

    #[serde(rename = "hit9_DmyPoly2")]
    pub hit9_dmy_poly2: i64,

    #[serde(rename = "hit10_DmyPoly2")]
    pub hit10_dmy_poly2: i64,

    #[serde(rename = "hit11_DmyPoly2")]
    pub hit11_dmy_poly2: i64,

    #[serde(rename = "hit12_DmyPoly2")]
    pub hit12_dmy_poly2: i64,

    #[serde(rename = "hit13_DmyPoly2")]
    pub hit13_dmy_poly2: i64,

    #[serde(rename = "hit14_DmyPoly2")]
    pub hit14_dmy_poly2: i64,

    #[serde(rename = "hit15_DmyPoly2")]
    pub hit15_dmy_poly2: i64,

    #[serde(rename = "hit4_hitType")]
    pub hit4_hit_type: i64,

    #[serde(rename = "hit5_hitType")]
    pub hit5_hit_type: i64,

    #[serde(rename = "hit6_hitType")]
    pub hit6_hit_type: i64,

    #[serde(rename = "hit7_hitType")]
    pub hit7_hit_type: i64,

    #[serde(rename = "hit8_hitType")]
    pub hit8_hit_type: i64,

    #[serde(rename = "hit9_hitType")]
    pub hit9_hit_type: i64,

    #[serde(rename = "hit10_hitType")]
    pub hit10_hit_type: i64,

    #[serde(rename = "hit11_hitType")]
    pub hit11_hit_type: i64,

    #[serde(rename = "hit12_hitType")]
    pub hit12_hit_type: i64,

    #[serde(rename = "hit13_hitType")]
    pub hit13_hit_type: i64,

    #[serde(rename = "hit14_hitType")]
    pub hit14_hit_type: i64,

    #[serde(rename = "hit15_hitType")]
    pub hit15_hit_type: i64,

    #[serde(rename = "hti4_Priority")]
    pub hti4_priority: i64,

    #[serde(rename = "hti5_Priority")]
    pub hti5_priority: i64,

    #[serde(rename = "hti6_Priority")]
    pub hti6_priority: i64,

    #[serde(rename = "hti7_Priority")]
    pub hti7_priority: i64,

    #[serde(rename = "hti8_Priority")]
    pub hti8_priority: i64,

    #[serde(rename = "hti9_Priority")]
    pub hti9_priority: i64,

    #[serde(rename = "hti10_Priority")]
    pub hti10_priority: i64,

    #[serde(rename = "hti11_Priority")]
    pub hti11_priority: i64,

    #[serde(rename = "hti12_Priority")]
    pub hti12_priority: i64,

    #[serde(rename = "hti13_Priority")]
    pub hti13_priority: i64,

    #[serde(rename = "hti14_Priority")]
    pub hti14_priority: i64,

    #[serde(rename = "hti15_Priority")]
    pub hti15_priority: i64,

    pub def_sfx_material1: i64,

    pub def_se_material2: i64,

    pub def_sfx_material2: i64,

    pub atk_dark_correction: i64,

    pub atk_dark: i64,

    pub pad5: i64,

    pub is_disable_parry: i64,

    pub is_disable_both_hands_atk_bonus: i64,

    pub is_invalidated_by_no_damage_in_air: i64,

    pub pad2: i64,

    #[serde(rename = "dmgLevel_vsPlayer")]
    pub dmg_level_vs_player: i64,

    pub status_ailment_atk_power_correct_rate: i64,

    #[serde(rename = "spEffectAtkPowerCorrectRate_byPoint")]
    pub sp_effect_atk_power_correct_rate_by_point: i64,

    #[serde(rename = "spEffectAtkPowerCorrectRate_byRate")]
    pub sp_effect_atk_power_correct_rate_by_rate: i64,

    #[serde(rename = "spEffectAtkPowerCorrectRate_byDmg")]
    pub sp_effect_atk_power_correct_rate_by_dmg: i64,

    #[serde(rename = "atkBehaviorId_2")]
    pub atk_behavior_id_2: i64,

    pub throw_damage_attribute: i64,

    #[serde(rename = "statusAilmentAtkPowerCorrectRate_byPoint")]
    pub status_ailment_atk_power_correct_rate_by_point: i64,

    pub overwrite_attack_element_correct_id: i64,

    pub decal_base_id1: i64,

    pub decal_base_id2: i64,

    pub wep_regain_hp_scale: i64,

    pub atk_regain_hp: i64,

    pub regainable_time_scale: i64,

    pub regainable_hp_rate_scale: i64,

    pub regainable_slot_id: i64,

    pub sp_attribute_variation_value: i64,

    pub parry_forward_offset: i64,

    pub atk_super_armor_correction: f64,

    pub def_sfx_material_variation_value: i64,

    pub pad4: String,

    pub final_damage_rate_id: i64,

    pub sub_category3: i64,

    pub sub_category4: i64,

    pub pad7: String,
}

impl Searchable for AtkParamPc {
    fn matches(&self, search_field: &SearchField) -> bool {
        match search_field {
            SearchField::ID(id) => self.id == *id,
            SearchField::Name(name) => self.name == *name,
        }
    }
}
