// Auto-generated by generate_data.py; do not edit.
// Source: common\Bullet.json

use serde::{Deserialize, Serialize};

use crate::records::SearchField;
use crate::traits::Searchable;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Bullet {
    #[serde(rename = "ID")]
    pub id: i64,

    #[serde(rename = "Name")]
    pub name: String,

    #[serde(rename = "atkId_Bullet")]
    pub atk_id_bullet: i64,

    #[serde(rename = "sfxId_Bullet")]
    pub sfx_id_bullet: i64,

    #[serde(rename = "sfxId_Hit")]
    pub sfx_id_hit: i64,

    #[serde(rename = "sfxId_Flick")]
    pub sfx_id_flick: i64,

    pub life: f64,

    pub dist: f64,

    pub shoot_interval: f64,

    pub gravity_in_range: f64,

    pub gravity_out_range: f64,

    pub horming_stop_range: f64,

    pub init_vellocity: f64,

    pub accel_in_range: f64,

    pub accel_out_range: f64,

    pub max_vellocity: f64,

    pub min_vellocity: f64,

    pub accel_time: f64,

    pub homing_begin_dist: f64,

    pub hit_radius: f64,

    pub hit_radius_max: f64,

    pub spread_time: f64,

    pub exp_delay: i64,

    pub horming_offset_range: f64,

    pub dmg_hit_record_life_time: f64,

    pub external_force: f64,

    #[serde(rename = "spEffectIDForShooter")]
    pub sp_effect_id_for_shooter: i64,

    #[serde(rename = "autoSearchNPCThinkID")]
    pub auto_search_npc_think_id: i64,

    #[serde(rename = "HitBulletID")]
    pub hit_bullet_id: i64,

    pub sp_effect_id0: i64,

    pub sp_effect_id1: i64,

    pub sp_effect_id2: i64,

    pub sp_effect_id3: i64,

    pub sp_effect_id4: i64,

    pub num_shoot: i64,

    pub homing_angle: i64,

    pub shoot_angle: i64,

    pub shoot_angle_interval: i64,

    pub shoot_angle_x_interval: i64,

    pub damage_damp: i64,

    pub spel_damage_damp: i64,

    pub fire_damage_damp: i64,

    pub thunder_damage_damp: i64,

    pub stamina_damp: i64,

    pub knockback_damp: i64,

    #[serde(rename = "shootAngleXZ")]
    pub shoot_angle_xz: i64,

    pub lock_shoot_limit_ang: i64,

    pub pad2: i64,

    pub prev_velocity_dir_rate: i64,

    pub atk_attribute: i64,

    pub sp_attribute: i64,

    #[serde(rename = "Material_AttackType")]
    pub material_attack_type: i64,

    #[serde(rename = "Material_AttackMaterial")]
    pub material_attack_material: i64,

    pub is_penetrate_chr: i64,

    pub is_penetrate_obj: i64,

    pub may_remote_detonate: i64,

    pub pad: i64,

    pub launch_condition_type: i64,

    #[serde(rename = "FollowType")]
    pub follow_type: i64,

    #[serde(rename = "EmittePosType")]
    pub emitte_pos_type: i64,

    #[serde(rename = "isAttackSFX")]
    pub is_attack_sfx: i64,

    pub is_endless_hit: i64,

    pub is_penetrate_map: i64,

    pub is_hit_both_team: i64,

    pub is_use_shared_hit_list: i64,

    pub is_use_multi_dmy_poly_if_place: i64,

    pub is_hit_other_bullet_force_erase_a: i64,

    pub is_hit_other_bullet_force_erase_b: i64,

    pub is_hit_force_magic: i64,

    pub is_ignore_sfx_if_hit_water: i64,

    pub is_ignore_move_state_if_hit_water: i64,

    pub is_hit_dark_force_magic: i64,

    pub dmg_calc_side: i64,

    pub is_enable_auto_homing: i64,

    pub is_sync_bullet_culc_dumypoly_pos: i64,

    pub is_owner_override_init_angle: i64,

    pub is_inherit_sfx_to_child: i64,

    pub dark_damage_damp: i64,

    #[serde(rename = "bulletSfxDeleteType_byHit")]
    pub bullet_sfx_delete_type_by_hit: i64,

    #[serde(rename = "bulletSfxDeleteType_byLifeDead")]
    pub bullet_sfx_delete_type_by_life_dead: i64,

    pub target_y_offset_range: f64,

    pub shoot_angle_y_max_random: f64,

    pub shoot_angle_x_max_random: f64,

    pub interval_create_bullet_id: i64,

    pub interval_create_time_min: f64,

    pub interval_create_time_max: f64,

    pub prediction_shoot_observe_time: f64,

    pub interval_create_wait_time: f64,

    pub sfx_posture_type: i64,

    pub create_limit_group_id: i64,

    pub pad5: i64,

    pub is_inherit_speed_to_child: i64,

    #[serde(rename = "isDisableHitSfx_byChrAndObj")]
    pub is_disable_hit_sfx_by_chr_and_obj: i64,

    #[serde(rename = "isCheckWall_byCenterRay")]
    pub is_check_wall_by_center_ray: i64,

    pub is_hit_flare: i64,

    pub is_use_bullet_wall_filter: i64,

    pub is_disable_ai_projectile_dodge: i64,

    pub is_non_dependence_magic_for_funnle_num: i64,

    pub is_ai_interrupt_shoot_no_damage_bullet: i64,

    pub random_create_radius: f64,

    #[serde(rename = "followOffset_BaseHeight")]
    pub follow_offset_base_height: f64,

    #[serde(rename = "assetNo_Hit")]
    pub asset_no_hit: i64,

    pub life_random_range: f64,

    pub homing_angle_x: i64,

    pub ballistic_calc_type: i64,

    pub attach_effect_type: i64,

    #[serde(rename = "seId_Bullet1")]
    pub se_id_bullet1: i64,

    #[serde(rename = "seId_Bullet2")]
    pub se_id_bullet2: i64,

    #[serde(rename = "seId_Hit")]
    pub se_id_hit: i64,

    #[serde(rename = "seId_Flick")]
    pub se_id_flick: i64,

    pub howitzer_shoot_angle_x_min: i64,

    pub howitzer_shoot_angle_x_max: i64,

    pub howitzer_init_min_velocity: i64,

    pub howitzer_init_max_velocity: i64,

    #[serde(rename = "sfxId_ForceErase")]
    pub sfx_id_force_erase: i64,

    #[serde(rename = "bulletSfxDeleteType_byForceErase")]
    pub bullet_sfx_delete_type_by_force_erase: i64,

    pub pad3: i64,

    #[serde(rename = "followDmypoly_forSfxPose")]
    pub follow_dmypoly_for_sfx_pose: i64,

    #[serde(rename = "followOffset_Radius")]
    pub follow_offset_radius: f64,

    pub sp_bullet_dist_up_rate: i64,

    pub nolock_target_dist: i64,

    pub pad4: String,
}

impl Searchable for Bullet {
    fn matches(&self, search_field: &SearchField) -> bool {
        match search_field {
            SearchField::ID(id) => self.id == *id,
            SearchField::Name(name) => self.name == *name,
        }
    }
}
