// Auto-generated by generate_data.py; do not edit.
// Source: common\Magic.json

use serde::{Deserialize, Serialize};

use crate::records::SearchField;
use crate::traits::Searchable;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Magic {
    #[serde(rename = "ID")]
    pub id: i64,

    #[serde(rename = "Name")]
    pub name: String,

    #[serde(rename = "disableParam_NT")]
    pub disable_param_nt: i64,

    pub disable_param_reserve1: i64,

    pub disable_param_reserve2: String,

    pub yes_no_dialog_message_id: i64,

    pub limit_cancel_sp_effect_id: i64,

    pub sort_id: i64,

    pub requirement_luck: i64,

    pub ai_notify_type: i64,

    pub mp: i64,

    pub stamina: i64,

    pub icon_id: i64,

    pub behavior_id: i64,

    pub mtrl_item_id: i64,

    pub replace_magic_id: i64,

    pub max_quantity: i64,

    pub ref_category1: i64,

    pub over_dexterity: i64,

    pub ref_category2: i64,

    pub slot_length: i64,

    pub requirement_intellect: i64,

    pub requirement_faith: i64,

    pub analog_dexterity_min: i64,

    pub analog_dexterity_max: i64,

    pub ez_state_behavior_type: i64,

    pub ref_category3: i64,

    pub sp_effect_category: i64,

    pub ref_type: i64,

    pub opme_menu_type: i64,

    pub ref_category4: i64,

    pub has_sp_effect_type: i64,

    pub replace_category: i64,

    pub use_limit_category: i64,

    pub vow_type0: i64,

    pub vow_type1: i64,

    pub vow_type2: i64,

    pub vow_type3: i64,

    pub vow_type4: i64,

    pub vow_type5: i64,

    pub vow_type6: i64,

    pub vow_type7: i64,

    #[serde(rename = "enable_multi")]
    pub enable_multi: i64,

    #[serde(rename = "enable_multi_only")]
    pub enable_multi_only: i64,

    pub is_enchant: i64,

    pub is_shield_enchant: i64,

    #[serde(rename = "enable_live")]
    pub enable_live: i64,

    #[serde(rename = "enable_gray")]
    pub enable_gray: i64,

    #[serde(rename = "enable_friendly")]
    pub enable_friendly: i64,

    #[serde(rename = "enable_hostile")]
    pub enable_hostile: i64,

    pub disable_offline: i64,

    pub cast_resonance_magic: i64,

    #[serde(rename = "isValidTough_ProtSADmg")]
    pub is_valid_tough_prot_sa_dmg: i64,

    pub is_warp_magic: i64,

    pub enable_riding: i64,

    pub disable_riding: i64,

    pub is_use_no_attack_region: i64,

    #[serde(rename = "pad_1")]
    pub pad_1: i64,

    pub vow_type8: i64,

    pub vow_type9: i64,

    pub vow_type10: i64,

    pub vow_type11: i64,

    pub vow_type12: i64,

    pub vow_type13: i64,

    pub vow_type14: i64,

    pub vow_type15: i64,

    pub cast_sfx_id: i64,

    pub fire_sfx_id: i64,

    pub effect_sfx_id: i64,

    pub toughness_correct_rate: i64,

    #[serde(rename = "ReplacementStatusType")]
    pub replacement_status_type: i64,

    #[serde(rename = "ReplacementStatus1")]
    pub replacement_status1: i64,

    #[serde(rename = "ReplacementStatus2")]
    pub replacement_status2: i64,

    #[serde(rename = "ReplacementStatus3")]
    pub replacement_status3: i64,

    #[serde(rename = "ReplacementStatus4")]
    pub replacement_status4: i64,

    pub ref_category5: i64,

    #[serde(rename = "consumeSA")]
    pub consume_sa: i64,

    #[serde(rename = "ReplacementMagic1")]
    pub replacement_magic1: i64,

    #[serde(rename = "ReplacementMagic2")]
    pub replacement_magic2: i64,

    #[serde(rename = "ReplacementMagic3")]
    pub replacement_magic3: i64,

    #[serde(rename = "ReplacementMagic4")]
    pub replacement_magic4: i64,

    #[serde(rename = "mp_charge")]
    pub mp_charge: i64,

    #[serde(rename = "stamina_charge")]
    pub stamina_charge: i64,

    pub create_limit_group_id: i64,

    pub ref_category6: i64,

    pub sub_category1: i64,

    pub sub_category2: i64,

    pub ref_category7: i64,

    pub ref_category8: i64,

    pub ref_category9: i64,

    pub ref_category10: i64,

    pub ref_id1: i64,

    pub ref_id2: i64,

    pub ref_id3: i64,

    pub ai_use_judge_id: i64,

    pub ref_id4: i64,

    pub ref_id5: i64,

    pub ref_id6: i64,

    pub ref_id7: i64,

    pub ref_id8: i64,

    pub ref_id9: i64,

    pub ref_id10: i64,

    pub consume_type1: i64,

    pub consume_type2: i64,

    pub consume_type3: i64,

    pub consume_type4: i64,

    pub consume_type5: i64,

    pub consume_type6: i64,

    pub consume_type7: i64,

    pub consume_type8: i64,

    pub consume_type9: i64,

    pub consume_type10: i64,

    #[serde(rename = "consumeLoopMP_forMenu")]
    pub consume_loop_mp_for_menu: i64,

    pub pad: String,
}

impl Searchable for Magic {
    fn matches(&self, search_field: &SearchField) -> bool {
        match search_field {
            SearchField::ID(id) => self.id == *id,
            SearchField::Name(name) => self.name == *name,
        }
    }
}
